FROM rocker/verse
RUN R -e "install.packages(\"shiny\")"
RUN R -e "install.packages(\"FactoMineR\")"
RUN R -e "install.packages(\"factoextra\")"
RUN R -e "install.packages(\"ggmosaic\")"
RUN R -e "install.packages(\"fastDummies\")"
RUN Rscript --no-restore --no-save -e "tinytex::tlmgr_install(c(\"wrapfig\",\"ec\",\"ulem\",\"amsmath\",\"capt-of\"))"
RUN Rscript --no-restore --no-save -e "tinytex::tlmgr_install(c(\"hyperref\",\"iftex\",\"pdftexcmds\",\"infwarerr\"))"
RUN Rscript --no-restore --no-save -e "tinytex::tlmgr_install(c(\"kvoptions\",\"epstopdf\",\"epstopdf-pkg\"))"
RUN Rscript --no-restore --no-save -e "tinytex::tlmgr_install(c(\"hanging\",\"grfext\"))"
RUN Rscript --no-restore --no-save -e "tinytex::tlmgr_install(c(\"etoolbox\",\"xcolor\",\"geometry\",\"enumitem\"))"
RUN R -e "install.packages(\"pROC\")"
RUN R -e "install.packages(\"rpart\")"
RUN R -e "install.packages(\"rpart.plot\")"
RUN R -e "install.packages(\"gbm\")"
RUN Rscript --no-restore --no-save -e "tinytex::tlmgr_install(c(\"wrapfig\",\"subcaption\",\"pgfplotstable\",\"filecontents\"))"
RUN Rscript --no-restore --no-save -e "tinytex::tlmgr_install(c(\"longtable\",\"grfext\"))"
RUN Rscript --no-restore --no-save -e "tinytex::tlmgr_install(\"caption\")"
